-- MySQL Script generated by MySQL Workbench
-- gio 01 dic 2016 18:18:03 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema database_artisti
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `database_artisti` ;

-- -----------------------------------------------------
-- Schema database_artisti
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database_artisti` DEFAULT CHARACTER SET utf8 ;
USE `database_artisti` ;

-- -----------------------------------------------------
-- Table `Regione`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Regione` ;

CREATE TABLE IF NOT EXISTS `Regione` (
  `AbbNome` CHAR(3) NOT NULL COMMENT 'Abbreviazione del nome della regione',
  `Nome` VARCHAR(50) CHARACTER SET 'latin1' NOT NULL COMMENT 'Nome completo della regione',
  UNIQUE INDEX `abb_UNIQUE` (`AbbNome` ASC),
  PRIMARY KEY (`AbbNome`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Provincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Provincia` ;

CREATE TABLE IF NOT EXISTS `Provincia` (
  `Nome` VARCHAR(100) NOT NULL COMMENT 'Nome completo della provincia',
  `Sigla` CHAR(2) NOT NULL COMMENT 'Sigla della provincia',
  `Regione` CHAR(3) NOT NULL,
  PRIMARY KEY (`Sigla`),
  INDEX `fk_Regione_Provincia_idx` (`Regione` ASC),
  CONSTRAINT `fk_Regione_Provincia`
    FOREIGN KEY (`Regione`)
    REFERENCES `Regione` (`AbbNome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 111
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Band`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Band` ;

CREATE TABLE IF NOT EXISTS `Band` (
  `idBand` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Provincia` CHAR(2) NOT NULL,
  `Immagine` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Immagine profilo band',
  `DataIscrizione` DATETIME NOT NULL,
  PRIMARY KEY (`idBand`),
  INDEX `fk_Provincia_Band_idx` (`Provincia` ASC),
  CONSTRAINT `fk_Provincia_Band`
    FOREIGN KEY (`Provincia`)
    REFERENCES `Provincia` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabella dati generici di una band';


-- -----------------------------------------------------
-- Table `TipoContatto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TipoContatto` ;

CREATE TABLE IF NOT EXISTS `TipoContatto` (
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabella dei tipi di contatto, per distinguere tra mail, facebook, whatsapp, ecc... i vari contatti forniti';


-- -----------------------------------------------------
-- Table `ContattoBand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ContattoBand` ;

CREATE TABLE IF NOT EXISTS `ContattoBand` (
  `idContatto` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idBand` INT(10) UNSIGNED NOT NULL,
  `TipoContatto` VARCHAR(20) NOT NULL,
  `Contatto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idContatto`),
  INDEX `fk_tipoContatto_ContattoBand_idx` (`TipoContatto` ASC),
  INDEX `fk_idBand_ContattoBand` (`idBand` ASC),
  CONSTRAINT `fk_idBand_ContattoBand`
    FOREIGN KEY (`idBand`)
    REFERENCES `Band` (`idBand`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipoContatto_ContattoBand`
    FOREIGN KEY (`TipoContatto`)
    REFERENCES `TipoContatto` (`Nome`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Utente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Utente` ;

CREATE TABLE IF NOT EXISTS `Utente` (
  `Username` VARCHAR(25) NOT NULL COMMENT 'Username dell\'utente',
  `Email` VARCHAR(45) NOT NULL COMMENT 'email dell\'utente',
  `DataNascita` DATE NOT NULL COMMENT 'Anno di nascita dell\'utente',
  `Provincia` CHAR(2) NOT NULL COMMENT 'Permette di indicare il paese di abitazione',
  `DataIscrizione` DATE NOT NULL,
  `Immagine` VARCHAR(45) NULL DEFAULT NULL COMMENT 'NULL se immagine di default',
  `HashedPassword` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Username`),
  UNIQUE INDEX `username_UNIQUE` (`Username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`Email` ASC),
  INDEX `fk_Provincia_Utente_idx` (`Provincia` ASC),
  CONSTRAINT `fk_Provincia_Utente`
    FOREIGN KEY (`Provincia`)
    REFERENCES `Provincia` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabella dei dati base degli utenti';


-- -----------------------------------------------------
-- Table `ContattoUtente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ContattoUtente` ;

CREATE TABLE IF NOT EXISTS `ContattoUtente` (
  `idContatto` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID univoco del contatto',
  `Username` VARCHAR(25) NOT NULL COMMENT 'ID utente proprietario del contatto',
  `TipoContatto` VARCHAR(20) NOT NULL COMMENT 'Tipo di contatto',
  `Contatto` VARCHAR(45) NOT NULL COMMENT 'Stringa contenente il contatto',
  PRIMARY KEY (`idContatto`),
  INDEX `fk_tipoContatto_ContattoUtente_idx` (`TipoContatto` ASC),
  INDEX `fk_idUtente_ContattoUtente_idx` (`Username` ASC),
  CONSTRAINT `fk_idUtente_ContattoUtente`
    FOREIGN KEY (`Username`)
    REFERENCES `Utente` (`Username`)
    ON DELETE NO ACTION -- CASCADE?
    ON UPDATE NO ACTION, -- CASCADE?
  CONSTRAINT `fk_tipoContatto_ContattoUtente`
    FOREIGN KEY (`TipoContatto`)
    REFERENCES `TipoContatto` (`Nome`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabella dei contatti degli utenti';


-- -----------------------------------------------------
-- Table `GenereMusicale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GenereMusicale` ;

CREATE TABLE IF NOT EXISTS `GenereMusicale` (
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GenereBand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GenereBand` ;

CREATE TABLE IF NOT EXISTS `GenereBand` (
  `idBand` INT(10) UNSIGNED NOT NULL,
  `Genere` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBand`, `Genere`),
  INDEX `fk_Genere_GenereBand_idx` (`Genere` ASC),
  CONSTRAINT `fk_Genere_GenereBand`
    FOREIGN KEY (`Genere`)
    REFERENCES `GenereMusicale` (`Nome`)
    ON DELETE NO ACTION -- CASCADE?
    ON UPDATE NO ACTION, -- CASCADE?
  CONSTRAINT `fk_idBand_GenereBand`
    FOREIGN KEY (`idBand`)
    REFERENCES `Band` (`idBand`)
    ON DELETE NO ACTION -- CASCADE?
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `GenereUtente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GenereUtente` ;

CREATE TABLE IF NOT EXISTS `GenereUtente` (
  `UsernameUtente` VARCHAR(25) NOT NULL,
  `Genere` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UsernameUtente`, `Genere`),
  INDEX `fk_Genere_GenereUtente_idx` (`Genere` ASC),
  CONSTRAINT `fk_Genere_GenereUtente`
    FOREIGN KEY (`Genere`)
    REFERENCES `GenereMusicale` (`Nome`)
    ON DELETE NO ACTION -- CASCADE?
    ON UPDATE NO ACTION, -- CASCADE?
  CONSTRAINT `fk_usernameUtente_GenereUtente`
    FOREIGN KEY (`UsernameUtente`)
    REFERENCES `Utente` (`Username`)
    ON DELETE NO ACTION -- CASCADE?
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Ruolo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ruolo` ;

CREATE TABLE IF NOT EXISTS `Ruolo` (
  `Nome` VARCHAR(45) NOT NULL COMMENT 'Nome dello ruolo all\'interno della band',
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabella degli strumenti';


-- -----------------------------------------------------
-- Table `RichiestaMembro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RichiestaMembro` ;

CREATE TABLE IF NOT EXISTS `RichiestaMembro` (
  `idBand` INT(10) UNSIGNED NOT NULL,
  `RuoloRichiesto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBand`),
  INDEX `fk_RuoloRichiesto_RichiestaMembro_idx` (`RuoloRichiesto` ASC),
  CONSTRAINT `fk_RuoloRichiesto_RichiestaMembro`
    FOREIGN KEY (`RuoloRichiesto`)
    REFERENCES `Ruolo` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idBand`
    FOREIGN KEY (`idBand`)
    REFERENCES `Band` (`idBand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `RichiestaPartecipazione`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RichiestaPartecipazione` ;

CREATE TABLE IF NOT EXISTS `RichiestaPartecipazione` (
  `usernameUtente` VARCHAR(25) NOT NULL,
  `idGruppo` INT(10) UNSIGNED NOT NULL,
  `RichiestaDaGruppo` TINYINT(1) NOT NULL COMMENT 'Vero se il gruppo ha chiesto all\'utente,\nFalso se l\'utente ha chiesto al gruppo',
  PRIMARY KEY (`usernameUtente`, `idGruppo`),
  INDEX `fk_idBand_RichiestaGruppoUtente_idx` (`idGruppo` ASC),
  INDEX `fk_usernameUtente_RichiestaPartecipazione_idx` (`usernameUtente` ASC),
  CONSTRAINT `fk_idBand_RichiestaGruppoUtente`
    FOREIGN KEY (`idGruppo`)
    REFERENCES `Band` (`idBand`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usernameUtente_RichiestaPartecipazione`
    FOREIGN KEY (`usernameUtente`)
    REFERENCES `Utente` (`Username`)
    ON DELETE NO ACTION -- così un utente non può eliminare il proprio profilo (?)
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `UtenteMembroBand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UtenteMembroBand` ;

CREATE TABLE IF NOT EXISTS `UtenteMembroBand` (
  `UsernameUtente` VARCHAR(25) NOT NULL COMMENT 'ID utente',
  `idBand` INT(10) UNSIGNED NOT NULL COMMENT 'ID band a cui partecipa',
  `Ruolo` VARCHAR(45) NOT NULL COMMENT 'Ruolo all\'interno della band',
  PRIMARY KEY (`UsernameUtente`, `idBand`),
  INDEX `fk_idBand_UtenteMembroBand_idx` (`idBand` ASC),
  INDEX `fk_Ruolo_UtenteMembroBand_idx` (`Ruolo` ASC),
  CONSTRAINT `fk_Ruolo_UtenteMembroBand`
    FOREIGN KEY (`Ruolo`)
    REFERENCES `Ruolo` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idBand_UtenteMembroBand`
    FOREIGN KEY (`idBand`)
    REFERENCES `Band` (`idBand`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usernameUtente_UtenteMembroBand`
    FOREIGN KEY (`UsernameUtente`)
    REFERENCES `Utente` (`Username`)
    ON DELETE NO ACTION -- così un utente non può eliminare il proprio profilo (?)
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabella dei legami tra gli utenti e le band';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Regione`
-- -----------------------------------------------------
START TRANSACTION;
USE `database_artisti`;
INSERT INTO `Regione` (`AbbNome`, `Nome`) VALUES ('ABR', 'Abruzzo');
INSERT INTO `Regione` (`AbbNome`, `Nome`) VALUES ('BAS', 'Basilicata');
INSERT INTO `Regione` (`AbbNome`, `Nome`) VALUES ('CAL', 'Calabria');
INSERT INTO `Regione` (`AbbNome`, `Nome`) VALUES ('CAM', 'Campania');
INSERT INTO `Regione` (`AbbNome`, `Nome`) VALUES ('EMR', 'Emilia-Romagna');
INSERT INTO `Regione` (`AbbNome`, `Nome`) VALUES ('FVG', 'Friuli-Venezia Giulia');
INSERT INTO `Regione` (`AbbNome`, `Nome`) VALUES ('LAZ', 'Lazio');
INSERT INTO `Regione` (`AbbNome`, `Nome`) VALUES ('LIG', 'Liguria');
INSERT INTO `Regione` (`AbbNome`, `Nome`) VALUES ('LOM', 'Lombardia');
INSERT INTO `Regione` (`AbbNome`, `Nome`) VALUES ('MAR', 'Marche');
INSERT INTO `Regione` (`AbbNome`, `Nome`) VALUES ('MOL', 'Molise');
INSERT INTO `Regione` (`AbbNome`, `Nome`) VALUES ('PIE', 'Piemonte');
INSERT INTO `Regione` (`AbbNome`, `Nome`) VALUES ('PUG', 'Puglia');
INSERT INTO `Regione` (`AbbNome`, `Nome`) VALUES ('SAR', 'Sardegna');
INSERT INTO `Regione` (`AbbNome`, `Nome`) VALUES ('SIC', 'Sicilia');
INSERT INTO `Regione` (`AbbNome`, `Nome`) VALUES ('TOS', 'Toscana');
INSERT INTO `Regione` (`AbbNome`, `Nome`) VALUES ('TAA', 'Trentino-Alto Adige');
INSERT INTO `Regione` (`AbbNome`, `Nome`) VALUES ('UMB', 'Umbria');
INSERT INTO `Regione` (`AbbNome`, `Nome`) VALUES ('VDA', 'Valle d\'Aosta');
INSERT INTO `Regione` (`AbbNome`, `Nome`) VALUES ('VEN', 'Veneto');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Provincia`
-- -----------------------------------------------------
START TRANSACTION;
USE `database_artisti`;
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Chieti', 'CH', 'ABR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('L\'Aquila', 'AQ', 'ABR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Pescara', 'PE', 'ABR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Teramo', 'TE', 'ABR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Matera', 'MT', 'BAS');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Potenza', 'PZ', 'BAS');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Catanzaro', 'CZ', 'CAL');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Cosenza', 'CS', 'CAL');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Crotone', 'KR', 'CAL');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Reggio Calabria', 'RC', 'CAL');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Vibo Valentia', 'VV', 'CAL');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Avellino', 'AV', 'CAM');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Benevento', 'BN', 'CAM');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Caserta', 'CE', 'CAM');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Napoli', 'NA', 'CAM');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Salerno', 'SA', 'CAM');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Bologna', 'BO', 'EMR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Ferrara', 'FE', 'EMR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Forli Cesena', 'FC', 'EMR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Modena', 'MO', 'EMR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Parma', 'PR', 'EMR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Piacenza', 'PC', 'EMR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Ravenna', 'RA', 'EMR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Reggio Emilia', 'RE', 'EMR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Rimini', 'RN', 'EMR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Gorizia', 'GO', 'FVG');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Pordenone', 'PN', 'FVG');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Trieste', 'TS', 'FVG');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Udine', 'UD', 'FVG');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Frosinone', 'FR', 'LAZ');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Latina', 'LT', 'LAZ');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Rieti', 'RI', 'LAZ');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Roma', 'RM', 'LAZ');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Viterbo', 'VT', 'LAZ');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Genova', 'GE', 'LIG');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Imperia', 'IM', 'LIG');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('La Spezia', 'SP', 'LIG');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Savona', 'SV', 'LIG');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Bergamo', 'BG', 'LOM');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Brescia', 'BS', 'LOM');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Como', 'CO', 'LOM');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Cremona', 'CR', 'LOM');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Lecco', 'LC', 'LOM');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Lodi', 'LO', 'LOM');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Mantova', 'MN', 'LOM');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Milano', 'MI', 'LOM');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Monza e della Brianza', 'MB', 'LOM');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Pavia', 'PV', 'LOM');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Sondrio', 'SO', 'LOM');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Varese', 'VA', 'LOM');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Ancona', 'AN', 'MAR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Ascoli Piceno', 'AP', 'MAR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Fermo', 'FM', 'MAR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Macerata', 'MC', 'MAR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Pesaro e Urbino', 'PU', 'MAR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Campobasso', 'CB', 'MOL');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Isernia', 'IS', 'MOL');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Alessandria', 'AL', 'PIE');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Asti', 'AT', 'PIE');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Biella', 'BI', 'PIE');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Cuneo', 'CN', 'PIE');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Novara', 'NO', 'PIE');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Torino', 'TO', 'PIE');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Verbano-Cusio-Ossola', 'VB', 'PIE');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Vercelli', 'VC', 'PIE');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Bari', 'BA', 'PUG');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Barletta-Andria-Trani', 'BT', 'PUG');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Brindisi', 'BR', 'PUG');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Foggia', 'FG', 'PUG');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Lecce', 'LE', 'PUG');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Taranto', 'TA', 'PUG');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Cagliari', 'CA', 'SAR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Carbonia-Iglesias', 'CI', 'SAR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Medio Campidano', 'VS', 'SAR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Nuoro', 'NU', 'SAR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Ogliastra', 'OG', 'SAR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Olbia-Tempio', 'OT', 'SAR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Oristano', 'OR', 'SAR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Sassari', 'SS', 'SAR');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Agrigento', 'AG', 'SIC');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Caltanissetta', 'CL', 'SIC');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Catania', 'CT', 'SIC');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Enna', 'EN', 'SIC');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Messina', 'ME', 'SIC');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Palermo', 'PA', 'SIC');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Ragusa', 'RG', 'SIC');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Siracusa', 'SR', 'SIC');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Trapani', 'TP', 'SIC');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Arezzo', 'AR', 'TOS');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Firenze', 'FI', 'TOS');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Grosseto', 'GR', 'TOS');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Livorno', 'LI', 'TOS');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Lucca', 'LU', 'TOS');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Massa-Carrara', 'MS', 'TOS');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Pisa', 'PI', 'TOS');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Pistoia', 'PT', 'TOS');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Prato', 'PO', 'TOS');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Siena', 'SI', 'TOS');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Bolzano', 'BZ', 'TAA');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Trento', 'TN', 'TAA');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Perugia', 'PG', 'UMB');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Terni', 'TR', 'UMB');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Aosta', 'AO', 'VDA');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Belluno', 'BL', 'VEN');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Padova', 'PD', 'VEN');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Rovigo', 'RO', 'VEN');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Treviso', 'TV', 'VEN');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Venezia', 'VE', 'VEN');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Verona', 'VR', 'VEN');
INSERT INTO `Provincia` (`Nome`, `Sigla`, `Regione`) VALUES ('Vicenza', 'VI', 'VEN');

COMMIT;

