-- MySQL Script generated by MySQL Workbench
-- gio 17 nov 2016 09:27:52 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Utente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Utente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Utente` (
  `idUtente` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID univoco dell\'utente',
  `Username` VARCHAR(25) NOT NULL COMMENT 'Username dell\'utente',
  `Email` VARCHAR(45) NOT NULL COMMENT 'email dell\'utente',
  `AnnoNascita` VARCHAR(45) NOT NULL COMMENT 'Anno di nascita dell\'utente',
  PRIMARY KEY (`idUtente`),
  UNIQUE INDEX `username_UNIQUE` (`Username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB
COMMENT = 'Tabella dei dati base degli utenti';


-- -----------------------------------------------------
-- Table `mydb`.`Ruolo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ruolo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ruolo` (
  `idRuolo` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID univoco dello strumento',
  `Nome` VARCHAR(45) NOT NULL COMMENT 'Nome dello strumento',
  PRIMARY KEY (`idRuolo`),
  UNIQUE INDEX `nome_UNIQUE` (`Nome` ASC),
  UNIQUE INDEX `idRuolo_UNIQUE` (`idRuolo` ASC))
ENGINE = InnoDB
COMMENT = 'Tabella degli strumenti';


-- -----------------------------------------------------
-- Table `mydb`.`UtenteEsegueRuolo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UtenteEsegueRuolo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UtenteEsegueRuolo` (
  `idUtente` INT UNSIGNED NOT NULL,
  `idStrumento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idUtente`, `idStrumento`),
  INDEX `fk_idStruemtno_idx` (`idStrumento` ASC),
  CONSTRAINT `fk_idUtente_UtenteEsegueRuolo`
    FOREIGN KEY (`idUtente`)
    REFERENCES `mydb`.`Utente` (`idUtente`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idStrumento_UtenteEsegueRuolo`
    FOREIGN KEY (`idStrumento`)
    REFERENCES `mydb`.`Ruolo` (`idRuolo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabella di collegamento tra gli utenti e gli strumenti che suonano';


-- -----------------------------------------------------
-- Table `mydb`.`TipoContatto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TipoContatto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TipoContatto` (
  `idTipoContatto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idTipoContatto`),
  UNIQUE INDEX `nome_UNIQUE` (`Nome` ASC))
ENGINE = InnoDB
COMMENT = 'Tabella dei tipi di contatto, per distinguere tra mail, facebook, whatsapp, ecc... i vari contatti forniti';


-- -----------------------------------------------------
-- Table `mydb`.`ContattoUtente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ContattoUtente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ContattoUtente` (
  `idContatto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idUtente` INT UNSIGNED NOT NULL,
  `idTipoContatto` INT UNSIGNED NOT NULL,
  `Contatto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idContatto`),
  INDEX `fk_idTipoContatto_idx` (`idTipoContatto` ASC),
  CONSTRAINT `fk_idUtente_ContattoUtente`
    FOREIGN KEY (`idUtente`)
    REFERENCES `mydb`.`Utente` (`idUtente`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idTipoContattoUtente`
    FOREIGN KEY (`idTipoContatto`)
    REFERENCES `mydb`.`TipoContatto` (`idTipoContatto`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabella dei contatti degli utenti';


-- -----------------------------------------------------
-- Table `mydb`.`Band`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Band` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Band` (
  `idBand` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBand`))
ENGINE = InnoDB
COMMENT = 'Tabella dati generici di una band\n';


-- -----------------------------------------------------
-- Table `mydb`.`UtenteMembroBand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`UtenteMembroBand` ;

CREATE TABLE IF NOT EXISTS `mydb`.`UtenteMembroBand` (
  `idUtente` INT UNSIGNED NOT NULL,
  `idBand` INT UNSIGNED NOT NULL,
  `StrumentoSuonato` INT UNSIGNED NULL,
  PRIMARY KEY (`idUtente`, `idBand`),
  INDEX `fk_idBand_idx` (`idBand` ASC),
  INDEX `fk_Ruolo_idx` (`StrumentoSuonato` ASC),
  CONSTRAINT `fk_idUtente_UtenteMembroBand`
    FOREIGN KEY (`idUtente`)
    REFERENCES `mydb`.`Utente` (`idUtente`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idBand_UtenteMembroBand`
    FOREIGN KEY (`idBand`)
    REFERENCES `mydb`.`Band` (`idBand`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ruolo_UtenteMembroBand`
    FOREIGN KEY (`StrumentoSuonato`)
    REFERENCES `mydb`.`UtenteEsegueRuolo` (`idStrumento`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabella dei legami tra gli utenti e le band';


-- -----------------------------------------------------
-- Table `mydb`.`RichiesteBand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RichiesteBand` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RichiesteBand` (
  `idBand` INT UNSIGNED NOT NULL,
  `RuoloRichiesto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idBand`),
  INDEX `fk_RuoloRichiesto_idx` (`RuoloRichiesto` ASC),
  CONSTRAINT `fk_StrumentoRichiesto`
    FOREIGN KEY (`RuoloRichiesto`)
    REFERENCES `mydb`.`Ruolo` (`idRuolo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idBand`
    FOREIGN KEY (`idBand`)
    REFERENCES `mydb`.`Band` (`idBand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ContattoBand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ContattoBand` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ContattoBand` (
  `idContatto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idBand` INT UNSIGNED NOT NULL,
  `idTipoContatto` INT UNSIGNED NOT NULL,
  `Contatto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idContatto`),
  INDEX `fk_idTipoContato_idx` (`idTipoContatto` ASC),
  CONSTRAINT `fk_idBand_ContattoBand`
    FOREIGN KEY (`idBand`)
    REFERENCES `mydb`.`Band` (`idBand`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idTipo_ContattoBand`
    FOREIGN KEY (`idTipoContatto`)
    REFERENCES `mydb`.`TipoContatto` (`idTipoContatto`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`TipoContatto`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`TipoContatto` (`idTipoContatto`, `Nome`) VALUES (DEFAULT, 'Profilo Facebook');
INSERT INTO `mydb`.`TipoContatto` (`idTipoContatto`, `Nome`) VALUES (DEFAULT, 'Pagina Facebook');
INSERT INTO `mydb`.`TipoContatto` (`idTipoContatto`, `Nome`) VALUES (DEFAULT, 'Telefono');
INSERT INTO `mydb`.`TipoContatto` (`idTipoContatto`, `Nome`) VALUES (DEFAULT, 'Email');
INSERT INTO `mydb`.`TipoContatto` (`idTipoContatto`, `Nome`) VALUES (DEFAULT, 'Whatsapp');
INSERT INTO `mydb`.`TipoContatto` (`idTipoContatto`, `Nome`) VALUES (DEFAULT, 'Telegram');

COMMIT;

