-- MySQL Script generated by MySQL Workbench
-- mar 29 nov 2016 14:12:38 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema database_artisti
-- -----------------------------------------------------
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Regione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Regione` (
  `idRegione` INT(3) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID regione',
  `AbbreviazioneNome` CHAR(3) NOT NULL COMMENT 'Abbreviazione del nome della regione',
  `Nome` VARCHAR(200) CHARACTER SET 'latin1' NOT NULL COMMENT 'Nome completo della regione',
  PRIMARY KEY (`idRegione`),
  UNIQUE INDEX `abb_UNIQUE` (`AbbreviazioneNome` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Provincia` (
  `idProvincia` INT(4) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID univoco provincia',
  `idRegione` INT(3) UNSIGNED NOT NULL COMMENT 'ID della regione di appartenenza',
  `Nome` VARCHAR(200) NOT NULL COMMENT 'Nome completo della provincia',
  `Sigla` CHAR(2) NOT NULL COMMENT 'Sigla della provincia',
  PRIMARY KEY (`idProvincia`),
  UNIQUE INDEX `siglaProvincia_UNIQUE` (`Sigla` ASC),
  INDEX `fk_idRegione_Provincia_idx` (`idRegione` ASC),
  CONSTRAINT `fk_idRegione_Provincia`
    FOREIGN KEY (`idRegione`)
    REFERENCES `Regione` (`idRegione`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 111
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Band`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Band` (
  `idBand` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Provincia` CHAR(2) NOT NULL,
  `Immagine` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Immagine profilo band',
  `DataIscrizione` DATETIME NOT NULL,
  PRIMARY KEY (`idBand`),
  INDEX `fk_Provincia_Band_idx` (`Provincia` ASC),
  CONSTRAINT `fk_Provincia_Band`
    FOREIGN KEY (`Provincia`)
    REFERENCES `Provincia` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabella dati generici di una band';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TipoContatto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TipoContatto` (
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabella dei tipi di contatto, per distinguere tra mail, facebook, whatsapp, ecc... i vari contatti forniti';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ContattoBand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ContattoBand` (
  `idContatto` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idBand` INT(10) UNSIGNED NOT NULL,
  `TipoContatto` VARCHAR(20) NOT NULL,
  `Contatto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idContatto`),
  INDEX `fk_tipoContatto_ContattoBand_idx` (`TipoContatto` ASC),
  INDEX `fk_idBand_ContattoBand` (`idBand` ASC),
  CONSTRAINT `fk_idBand_ContattoBand`
    FOREIGN KEY (`idBand`)
    REFERENCES `Band` (`idBand`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipoContatto_ContattoBand`
    FOREIGN KEY (`TipoContatto`)
    REFERENCES `TipoContatto` (`Nome`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Utente` (
  `Username` VARCHAR(25) NOT NULL COMMENT 'Username dell\'utente',
  `Email` VARCHAR(45) NOT NULL COMMENT 'email dell\'utente',
  `DataNascita` DATE NOT NULL COMMENT 'Anno di nascita dell\'utente',
  `Provincia` CHAR(3) NOT NULL COMMENT 'Permette di indicare il paese di abitazione',
  `DataIscrizione` DATE NOT NULL,
  `Immagine` VARCHAR(45) NULL DEFAULT NULL COMMENT 'NULL se immagine di default',
  `HashedPassword` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Username`),
  UNIQUE INDEX `username_UNIQUE` (`Username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`Email` ASC),
  INDEX `fk_Provincia_Utente_idx` (`Provincia` ASC),
  CONSTRAINT `fk_Provincia_Utente`
    FOREIGN KEY (`Provincia`)
    REFERENCES `Provincia` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabella dei dati base degli utenti';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ContattoUtente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ContattoUtente` (
  `idContatto` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID univoco del contatto',
  `Username` VARCHAR(25) NOT NULL COMMENT 'ID utente proprietario del contatto',
  `TipoContatto` VARCHAR(20) NOT NULL COMMENT 'Tipo di contatto',
  `Contatto` VARCHAR(45) NOT NULL COMMENT 'Stringa contenente il contatto',
  PRIMARY KEY (`idContatto`),
  INDEX `fk_tipoContatto_ContattoUtente_idx` (`TipoContatto` ASC),
  INDEX `fk_idUtente_ContattoUtente_idx` (`Username` ASC),
  CONSTRAINT `fk_idUtente_ContattoUtente`
    FOREIGN KEY (`Username`)
    REFERENCES `Utente` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipoContatto_ContattoUtente`
    FOREIGN KEY (`TipoContatto`)
    REFERENCES `TipoContatto` (`Nome`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabella dei contatti degli utenti';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GenereMusicale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GenereMusicale` (
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GenereBand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GenereBand` (
  `idBand` INT(10) UNSIGNED NOT NULL,
  `Genere` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBand`, `Genere`),
  INDEX `fk_Genere_GenereBand_idx` (`Genere` ASC),
  CONSTRAINT `fk_Genere_GenereBand`
    FOREIGN KEY (`Genere`)
    REFERENCES `GenereMusicale` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idBand_GenereBand`
    FOREIGN KEY (`idBand`)
    REFERENCES `Band` (`idBand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `GenereUtente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GenereUtente` (
  `UsernameUtente` VARCHAR(25) NOT NULL,
  `Genere` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UsernameUtente`, `Genere`),
  INDEX `fk_Genere_GenereUtente_idx` (`Genere` ASC),
  CONSTRAINT `fk_Genere_GenereUtente`
    FOREIGN KEY (`Genere`)
    REFERENCES `GenereMusicale` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usernameUtente_GenereUtente`
    FOREIGN KEY (`UsernameUtente`)
    REFERENCES `Utente` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Ruolo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ruolo` (
  `Nome` VARCHAR(45) NOT NULL COMMENT 'Nome dello ruolo all\'interno della band',
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabella degli strumenti';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `RichiestaMembro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RichiestaMembro` (
  `idBand` INT(10) UNSIGNED NOT NULL,
  `RuoloRichiesto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBand`),
  INDEX `fk_RuoloRichiesto_RichiestaMembro_idx` (`RuoloRichiesto` ASC),
  CONSTRAINT `fk_RuoloRichiesto_RichiestaMembro`
    FOREIGN KEY (`RuoloRichiesto`)
    REFERENCES `Ruolo` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idBand`
    FOREIGN KEY (`idBand`)
    REFERENCES `Band` (`idBand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `RichiestaPartecipazione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RichiestaPartecipazione` (
  `usernameUtente` VARCHAR(25) NOT NULL,
  `idGruppo` INT(10) UNSIGNED NOT NULL,
  `RichiestaDaGruppo` TINYINT(1) NOT NULL COMMENT 'Vero se il gruppo ha chiesto all\'utente,\nFalso se l\'utente ha chiesto al gruppo',
  PRIMARY KEY (`usernameUtente`, `idGruppo`),
  INDEX `fk_idBand_RichiestaGruppoUtente_idx` (`idGruppo` ASC),
  INDEX `fk_usernameUtente_RichiestaPartecipazione_idx` (`usernameUtente` ASC),
  CONSTRAINT `fk_idBand_RichiestaGruppoUtente`
    FOREIGN KEY (`idGruppo`)
    REFERENCES `Band` (`idBand`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usernameUtente_RichiestaPartecipazione`
    FOREIGN KEY (`usernameUtente`)
    REFERENCES `Utente` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `UtenteMembroBand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UtenteMembroBand` (
  `UsernameUtente` VARCHAR(25) NOT NULL COMMENT 'ID utente',
  `idBand` INT(10) UNSIGNED NOT NULL COMMENT 'ID band a cui partecipa',
  `Ruolo` VARCHAR(45) NOT NULL COMMENT 'Ruolo all\'interno della band',
  PRIMARY KEY (`UsernameUtente`, `idBand`),
  INDEX `fk_idBand_UtenteMembroBand_idx` (`idBand` ASC),
  INDEX `fk_Ruolo_UtenteMembroBand_idx` (`Ruolo` ASC),
  CONSTRAINT `fk_Ruolo_UtenteMembroBand`
    FOREIGN KEY (`Ruolo`)
    REFERENCES `Ruolo` (`Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idBand_UtenteMembroBand`
    FOREIGN KEY (`idBand`)
    REFERENCES `Band` (`idBand`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usernameUtente_UtenteMembroBand`
    FOREIGN KEY (`UsernameUtente`)
    REFERENCES `Utente` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabella dei legami tra gli utenti e le band';

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
